ktor:
    deployment:
        port: 8080
    application:
        modules:
            - org.jetbrains.kotlinApp.backend.MainKt.conferenceBackend

sessionize:
    url: "https://sessionize.com/api/v2/cdftbl11/view/All"
    imagesUrl: "https://sessionize.com/image/"
    interval: 60

database:
    host: "db:5432"
    user: "postgres"
    password: "postgres"
    database: "kotlinconfg"

    poolSize: 5

service:
    environment: production
    secret: "admin"
